[package]
name = "noiseexplorer_k1n"
version = "0.1.2"
authors = ["Symbolic Software <georgio@symbolic.software>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
blake2-rfc = "0.2.18"
rust-crypto = "0.2.36"
hacl-star = ">=0.0.14"
hex = ">=0.3.2"
rand = ">=0.6.5"
zeroize = ">=0.6.0"
